baseURL = 'https://binjang.github.io/'
languageCode = 'en-us'
title = 'Infinite Horizon'
theme = 'PaperMod'
ignorefiles = ['content/templates']

[languages]
    [languages.ko]
    contentDir = 'content/ko'
    languageName = '🇰🇷 한국어'

    [languages.ko.params.homeInfoMode]
    enabled = true

    [languages.ko.params.homeInfoParams]
    Title = "Hi there wave"
    Content = "Can be Info, links, about..."

    [[languages.ko.params.socialIcons]]
    name = "<platform>"
    url = "<link>"

    [[languages.ko.params.socialIcons]]
    name = "<platform 2>"
    url = "<link2>"
    [[languages.ko.params.homeInfoMode.buttons]]
    name = 'Archive'
    url = '/ko/archive'
    [[languages.ko.params.homeInfoMode.buttons]]
    name = 'Posts'
    url = '/ko/posts'


    [languages.en]
    contentDir = 'content/en'
    languageName = '🇺🇸 English'

    [languages.en.params.homeInfoMode]
    enabled = true

    [languages.en.params.homeInfoParams]
    Title = "Hi there wave"
    Content = "Can be Info, links, about..."

    [[languages.en.params.socialIcons]]
    name = "<platform>"
    url = "<link>"

    [[languages.en.params.socialIcons]]
    name = "<platform 2>"
    url = "<link2>"

    [[languages.en.params.homeInfoMode.buttons]]
    name = 'Archive'
    url = '/en/archive'

    [[languages.en.params.homeInfoMode.buttons]]
    name = 'Posts'
    url = '/en/posts'