baseURL = 'https://binjang.github.io/'
languageCode = 'en-us'
title = 'Infinite Horizon'
theme = 'PaperMod'
ignorefiles = ['content/templates']
enableEmoji = true

[languages]
    [languages.ko]
    contentDir = 'content/ko'
    languageName = ':ko:'
    languageAltTitle = 'Korean'

    [languages.ko.params]
    defaultTheme = 'auto'
    ShowShareButtons = true
    ShowReadingTime = true

    [languages.ko.params.homeInfoMode]
    enabled = true

    [languages.ko.params.homeInfoParams]
    Title = "Welcome to my Blog! :raising_hand_man:"
    Content = """
    This Blog is for sharing my idea notes and personal projects' progresses.
    You can find links to my portfolio and other SNS below.
    """

    [[languages.ko.params.socialIcons]]
    name = "github"
    url = "https://github.com/binjang"

    [[languages.ko.params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bin-jang/"

    [[languages.ko.params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/binj0313"

    [[languages.ko.params.homeInfoMode.buttons]]
    name = 'Archive'
    url = '/ko/archive'

    [[languages.ko.params.homeInfoMode.buttons]]
    name = 'Posts'
    url = '/ko/posts'


    [languages.en]
    contentDir = 'content/en'
    languageName = ':en:'
    languageAltTitle = 'English'

    [languages.en.params.homeInfoMode]
    enabled = true

    [languages.en.params.homeInfoParams]
    Title = "Welcome to my Blog! :raising_hand_man:"
    Content = """
    This Blog is for sharing my idea notes and personal projects' progresses.
    You can find links to my portfolio and other SNS below.
    """

    [[languages.en.params.socialIcons]]
    name = "github"
    url = "https://github.com/binjang"

    [[languages.en.params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bin-jang/"

    [[languages.en.params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/binj0313"

    [[languages.en.params.homeInfoMode.buttons]]
    name = 'Archive'
    url = '/en/archive'

    [[languages.en.params.homeInfoMode.buttons]]
    name = 'Posts'
    url = '/en/posts'