baseURL = 'https://binjang.github.io/'
languageCode = 'en-us'
title = 'Infinite Horizon'
theme = 'PaperMod'
ignorefiles = ['content/templates']
enableEmoji = true
enableRobotsTXT = true

[languages]
    [languages.ko]
    contentDir = 'content/ko'
    languageName = ':ko:'
    weight = 2


    [languages.ko.params]
    defaultTheme = 'auto'
    author = '장빈'
    ShowReadingTime = true
    comments = true
    hideSummary = false
    languageAltTitle = 'Korean'
    ShowToc = true

    [languages.ko.params.homeInfoMode]
    enabled = true

    [languages.ko.params.homeInfoParams]
    Title = "Welcome to my Blog! :raising_hand_man:"
    Content = """
    This Blog is for sharing my idea notes and personal projects' progresses.
    You can find links to my portfolio and other SNS below.
    """

    [languages.ko.taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

    [[languages.ko.menu.main]]
    name = "Archive"
    url = "archives"
    weight = 5

    [[languages.ko.menu.main]]
    name = "Search"
    url = "search/"
    weight = 10

    [[languages.ko.menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 10

    [[languages.ko.params.socialIcons]]
    name = "cv"
    url = "https://binjang.notion.site/Hi-I-m-Bin-39a00a62403844ec900bfbaa21859645?pvs=4"

    [[languages.ko.params.socialIcons]]
    name = "email"
    url = "mailto:bjang98@gmail.com"

    [[languages.ko.params.socialIcons]]
    name = "github"
    url = "https://github.com/binjang"

    [[languages.ko.params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bin-jang/"

    [[languages.ko.params.homeInfoMode.buttons]]
    name = 'Archive'
    url = '/ko/archive'

    [[languages.ko.params.homeInfoMode.buttons]]
    name = 'Posts'
    url = '/ko/posts'


    [languages.en]
    contentDir = 'content/en'
    languageName = ':en:'
    weight = 1


    [languages.en.params]
    defaultTheme = 'auto'
    author = 'Bin Jang'
    ShowReadingTime = true
    comments = true
    hideSummary = false
    languageAltTitle = 'English'
    ShowToc = true

    [languages.en.params.homeInfoMode]
    enabled = true

    [languages.en.params.homeInfoParams]
    Title = "Welcome to my Blog! :raising_hand_man:"
    Content = """
    This Blog is for sharing my idea notes and personal projects' progresses.
    You can find links to my portfolio and other SNS below.
    """

    [languages.en.taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

    [[languages.en.menu.main]]
    name = "Archive"
    url = "archives"
    weight = 5

    [[languages.en.menu.main]]
    name = "Search"
    url = "search/"
    weight = 10

    [[languages.en.menu.main]]
    name = "Tags"
    url = "tags/"
    weight = 10

    [[languages.en.params.socialIcons]]
    name = "cv"
    url = "https://binjang.notion.site/Hi-I-m-Bin-39a00a62403844ec900bfbaa21859645?pvs=4"

    [[languages.en.params.socialIcons]]
    name = "email"
    url = "mailto:bjang98@gmail.com"

    [[languages.en.params.socialIcons]]
    name = "github"
    url = "https://github.com/binjang"

    [[languages.en.params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bin-jang/"

    [[languages.en.params.homeInfoMode.buttons]]
    name = 'Archive'
    url = '/en/archive'

    [[languages.en.params.homeInfoMode.buttons]]
    name = 'Posts'
    url = '/en/posts'